### ISSUE TITLE
Cannot Get /list path

### ISSUE THREAD

**Issue by sekar-worx** [DevWurm/angular-2-electron-seed#9]
Hey, 
 
I am facing an issue while using route. Once i refresh the page manually in electron it shows error like **Cannot GET /list path**
please help me in this.

**Comment by DevWurm** [comment]
As mentioned in [this thread](https://github.com/angular/angular/issues/13948#issuecomment-302727428), you might try to realize the routing via url fragment identifiers instead of subroutes, when using Electron. Using subroutes may lead Electron to load a "file" which doesn't exist and as far as I know, there is no Electron option to re-route this misleading requests.

So you might import your routing module with this option:
```js
RouterModule.forRoot(routes,{useHash:true})
```

Please let us know, if it worked!

**Comment by sekar-worx** [comment]
Thanks, it fixed now
